<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.11" />
    <PackageReference Include="LZMA-SDK" Version="22.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.2" />
    <PackageReference Include="SevenZip" Version="19.0.0" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
    <PackageReference Include="System.Reactive" Version="6.1.0" />
    <PackageReference Include="System.Reactive.Linq" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Tomlyn" Version="0.19.0" />
    <PackageReference Include="UltimateLogSystem" Version="1.1.0" />
  </ItemGroup>

</Project>
