<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GenHTTP.Core" Version="10.4.0" />
    <PackageReference Include="GenHTTP.Modules.Functional" Version="10.4.0" />
    <PackageReference Include="GenHTTP.Modules.Layouting" Version="10.4.0" />
    <PackageReference Include="GenHTTP.Modules.StaticWebsites" Version="10.4.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="NUnit" Version="4.4.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PCL.Neo.Core\PCL.Neo.Core.csproj" />
    <ProjectReference Include="..\PCL.Neo\PCL.Neo.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core\Models\Minecraft\Game\Data\" />
    <Folder Include="Core\Models\Utils\Logger\" />
    <Folder Include="Core\Service\Game\" />
  </ItemGroup>

</Project>
